### ISSUE TITLE
エラー「~.__init__() missing 1 required keyword-only argument: 'type'」

### ISSUE THREAD

**Issue by aopontan-b** [aopontan-b/create-adf-python#1]
[クイック スタート:Python を使用してデータ ファクトリとパイプラインを作成する](https://learn.microsoft.com/ja-jp/azure/data-factory/quickstart-create-data-factory-python) の内容通りに実装したが、プログラムを実行したところで、以下のエラーが発生した
<img width="703" alt="LinkedServiceReferenceエラー" src="https://github.com/aopontan-b/create-adf-python/assets/134246891/c48e8c7c-6b52-4c20-9e2e-7d6f7365f42c">

### 環境
- Windows11 WSL2 Ubuntu 22.04.2 LTS
- python 3.10.6
- requirements.txt
```
azure-identity==1.13.0
azure-mgmt-datafactory==3.1.0
azure-mgmt-resource==23.0.1
python-dotenv==1.0.0
```

**Comment by aopontan-b** [comment]
Microsoftのリファレンス [LinkedServiceReference Class](https://learn.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.models.linkedservicereference?view=azure-python) をみたら、
`type`パラメーターを指定しないといけないっぽい？

<img width="462" alt="image" src="https://github.com/aopontan-b/create-adf-python/assets/134246891/f1195015-72e1-47bd-933e-59911aaf7bfe">

**Comment by aopontan-b** [comment]
試しに[LinkedServiceReference関数の引数に「type="LinkedServiceReference"」を追加](https://github.com/aopontan-b/create-adf-python/commit/d2f8ea8b124beba2e48caca7442f84fb464a39fc?diff=split)してみたら、該当箇所のエラーがなくなった

**Comment by aopontan-b** [comment]
別の箇所で先ほどと同じエラーがでるようになった

```
Traceback (most recent call last):
  File "/home/aopontan/workspace/create-adf-python/datafactory.py", line 142, in <module>
    main()
  File "/home/aopontan/workspace/create-adf-python/datafactory.py", line 113, in main
    dsin_ref = DatasetReference(reference_name=ds_name)
TypeError: DatasetReference.__init__() missing 1 required keyword-only argument: 'type'
```

**Comment by aopontan-b** [comment]
これも同じように引数にtypeパラメータを指定してみる
あと、もう一箇所`DatasetReference`を使っているところがあるので、そこも一緒に指定する

**Comment by aopontan-b** [comment]
実行したところ、Data Factoryを構築することができた。

```
        Pipeline run status: Succeeded
Datetime with no tzinfo will be considered UTC.
Datetime with no tzinfo will be considered UTC.

        Activity run details

        Activity run status: Succeeded
        Number of bytes read: 18
        Number of bytes written: 18
        Copy duration: 8
```

**Comment by aopontan-b** [comment]
Microsoftの[サイト](https://learn.microsoft.com/ja-jp/azure/data-factory/quickstart-create-data-factory-python#create-a-dataset-for-source-azure-blob)では、
LinkedServiceReference関数の引数に「type="LinkedServiceReference"」を指定していない。
サイトの情報が古いのかな？

<img width="945" alt="image" src="https://github.com/aopontan-b/create-adf-python/assets/134246891/2576e7a6-9b4d-45fc-a287-4c4c9ffd1252">
